- hosts: my_vm
  become: yes
  tasks:
    - name: Pull MySQL Docker image
      community.docker.docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Run MySQL container
      community.docker.docker_container:
        name: mysql-server
        image: mysql:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: "root_password"
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix"
        ports:
          - "3308:3306"
        
    - name: Pull Zabbix Docker image
      community.docker.docker_image:
        name: zabbix/zabbix-server-mysql
        tag: latest
        source: pull

    - name: Run Zabbix container
      community.docker.docker_container:
        name: zabbix
        image: zabbix/zabbix-server-mysql:latest
        state: started
        ports:
          - "8090:80"
          - "10056:10051"
        env:
          DB_SERVER_HOST: "mysql-server"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix"
          MYSQL_DATABASE: "zabbix"

    - name: Pull Nagios Docker image
      community.docker.docker_image:
        name: jasonrivers/nagios
        tag: latest
        source: pull

    - name: Run Nagios container
      community.docker.docker_container:
        name: nagios
        image: jasonrivers/nagios:latest
        state: started
        ports:
          - "8091:80"

    - name: Pull Prometheus Docker image
      community.docker.docker_image:
        name: prom/prometheus
        tag: v2.30.3
        source: pull

    - name: Run Prometheus container
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:v2.30.3
        state: started
        ports:
          - "8092:9090"
